(function(){
    // Wait until DOM ready
    function ready(fn) {
        if (document.readyState != 'loading') fn();
        else document.addEventListener('DOMContentLoaded', fn);
    }

    ready(function(){
        // Create floating panel
        var panel = document.createElement('div');
        panel.id = 'agmelhorenvio-selected-sum';
        panel.style.position = 'fixed';
        panel.style.right = '20px';
        panel.style.bottom = '20px';
        panel.style.zIndex = '9999';
        panel.style.background = '#fff';
        panel.style.border = '1px solid #ddd';
        panel.style.padding = '10px 14px';
        panel.style.boxShadow = '0 2px 8px rgba(0,0,0,0.12)';
        panel.style.borderRadius = '4px';
        panel.style.display = 'none';
        panel.style.minWidth = '180px';

        var title = document.createElement('div');
        title.style.fontSize = '13px';
        title.style.color = '#333';
        title.style.marginBottom = '6px';
        title.textContent = 'Total selecionado';

        var amount = document.createElement('div');
        amount.id = 'agmelhorenvio-selected-sum-amount';
        amount.style.fontSize = '18px';
        amount.style.fontWeight = '600';
        amount.style.color = '#2a7ae2';
        amount.textContent = 'R$ 0,00';

        panel.appendChild(title);
        panel.appendChild(amount);
        document.body.appendChild(panel);

        // Helper to parse price strings like "R$ 1.234,56" or "1.234,56"
        function parsePrice(text) {
            if (!text) return 0;
            // remove currency symbol and spaces
            text = text.replace(/[R$\s]/g, '');
            // replace thousand separators '.' and decimal comma ','
            text = text.replace(/\./g, '').replace(/,/g, '.');
            var n = parseFloat(text);
            return isNaN(n) ? 0 : n;
        }

        function formatPriceBR(value) {
            return 'R$ ' + value.toFixed(2).replace('.', ',').replace(/(\d)(?=(\d{3})+\b)/g, '$1.');
        }

        // Find the table containing the list
        var table = document.querySelector('.table, table.table');
        if (!table) return;

        // The list may be generated by PrestaShop: check for checkboxes with name ending with []
        function findCheckboxes() {
            // typical PrestaShop list checkboxes have name like "labelBox[]" or "{this.opts.name}[]"
            return Array.prototype.slice.call(table.querySelectorAll('input[type=checkbox]'))
                .filter(function(cb){
                    // filter out header "checkme" and unrelated checkboxes
                    if (!cb.name) return false;
                    if (cb.id === 'checkme') return false;
                    // only boxes with [] (bulk) or class groupBox
                    return cb.name.indexOf('[]') !== -1 || cb.classList.contains('groupBox') || cb.classList.contains('bulk');
                });
        }

        function findPriceCellForCheckbox(cb) {
            // Traverse up to row, then find the cell that contains price text
            var row = cb.closest('tr');
            if (!row) return null;

            // prefer cell with class containing 'price' or header title
            var priceCell = row.querySelector('td.price, td[class*="price"], td[class*="fixed-width-md"]');
            if (priceCell) return priceCell;

            // fallback: try to find a cell whose text matches currency pattern
            var tds = row.querySelectorAll('td');
            for (var i = 0; i < tds.length; i++) {
                var txt = tds[i].textContent || '';
                if (/\d+[.,]\d{2}/.test(txt)) return tds[i];
            }

            return null;
        }

        function updateSum() {
            var checkboxes = findCheckboxes();
            var total = 0;
            var any = false;

            checkboxes.forEach(function(cb){
                if (cb.checked) {
                    any = true;
                    var cell = findPriceCellForCheckbox(cb);
                    var text = cell ? cell.textContent.trim() : '';
                    total += parsePrice(text);
                }
            });

            if (any) {
                amount.textContent = formatPriceBR(total);
                panel.style.display = 'block';
            } else {
                panel.style.display = 'none';
            }
        }

        // Attach change listeners
        function bind() {
            var checkboxes = findCheckboxes();
            checkboxes.forEach(function(cb){
                cb.removeEventListener('change', updateSum);
                cb.addEventListener('change', updateSum);
            });

            // also handle select-all checkbox
            var headerCheck = document.querySelector('input#checkme');
            if (headerCheck) {
                headerCheck.removeEventListener('click', updateSum);
                headerCheck.addEventListener('click', function(){
                    // small timeout to let checkDelBoxes run
                    setTimeout(updateSum, 50);
                });
            }
        }

        // initial bind
        bind();

        // In case list is re-rendered by ajax, rebind periodically for a short time
        var tries = 0;
        var rebinder = setInterval(function(){
            tries++;
            bind();
            updateSum();
            if (tries > 20) clearInterval(rebinder);
        }, 500);

        // Also observe DOM mutations in the table to rebind when rows change
        try {
            var observer = new MutationObserver(function(m){
                bind();
                updateSum();
            });
            observer.observe(table, {childList: true, subtree: true});
        } catch(e){}

    });
})();
